### ISSUE TITLE
Implement graph searching algorithms in java

### ISSUE THREAD

**Issue by whyanujjwhy** [BimalRajGyawali/hacktoberfest-java#113]
Hi @BimalRajGyawali I would like to add few graph search algos like bfs, dfs in java. Could you please assign it to me? Thanks!

**Comment by BimalRajGyawali** [comment]
Sure. Add them under _org.examples.algorithms_ package. Create subpackages if necessary.

Please do this in multiple PRs to avoid PR with large number of changes, which are difficult to review. Thanks.

**Comment by Nikhil-2002** [comment]
Hi @BimalRajGyawali I would like to add some searching algorithms. Could you please assign it to me? Thanks!

**Comment by whyanujjwhy** [comment]
Okay sure, thanks!
Will do the needful.

**Comment by BimalRajGyawali** [comment]
Hi @Nikhil-2002 , which algorithms you want to implement?

**Comment by Nikhil-2002** [comment]
@BimalRajGyawali  Dijkstra's algorithm

**Comment by BimalRajGyawali** [comment]
@

**Comment by BimalRajGyawali** [comment]
Hi @Nikhil-2002, you can implement it. Make sure to follow the naming convention and place the class in appropriate package.

**Comment by BimalRajGyawali** [comment]
@Nikhil-2002 Also, include only one file in PR.

**Comment by Nikhil-2002** [comment]
hey @BimalRajGyawali  plz review and accept PR . Thanks !!

**Comment by BimalRajGyawali** [comment]
Hi @Nikhil-2002 , I have requested changes. Please do the needful.

**Comment by Nikhil-2002** [comment]
hey, @BimalRajGyawal i have done changes plz review and accept PR . Thanks !!
