### ISSUE TITLE
Create a Map using Factory Method

### ISSUE THREAD

**Issue by BimalRajGyawali** [BimalRajGyawali/hacktoberfest-java#12]
Map can be created using static factory method _of_ in the following way: 

_Map.of(k1, v1, k2, v2)_ where k1, k2 are keys and v1, v2 are corresponding values.

Add a program to create a map using this method.

**Comment by semnim** [comment]
Hey! I created a PR for this issue.

**Comment by BimalRajGyawali** [comment]
Merged. Thanks for contributing
