### ISSUE TITLE
Singleton Design Pattern

### ISSUE THREAD

**Issue by BimalRajGyawali** [BimalRajGyawali/hacktoberfest-java#130]
Add an example showing Singleton Design Pattern. The code should be placed inside _org.example.designpatterns.singleton_ package.

**Comment by Nikhil-2002** [comment]
hey @BimalRajGyawali please assign me this issue I can try

**Comment by Nikhil-2002** [comment]
Hey @BimalRajGyawali please review and accept PR

**Comment by BimalRajGyawali** [comment]
Hi @Nikhil-2002, I have reviewed your PR. I have closed it with comments. Thanks
