### ISSUE TITLE
Prim's Algorithm in Java

### ISSUE THREAD

**Issue by PalaVenkiReddy** [BimalRajGyawali/hacktoberfest-java#142]
I want to contribute to Prim's Algorithm in Java. Please assign this issue to me @BimalRajGyawali

**Comment by Nikhil-2002** [comment]
I want to contribute to Prim's Algorithm in Java. Please assign this issue to me @BimalRajGyawali

**Comment by BimalRajGyawali** [comment]
Hi @Nikhil-2002, you are already assigned to other issues so I am assigning this one to @PalaVenkiReddy .Thanks.
