### ISSUE TITLE
Update README with links to packages/folders

### ISSUE THREAD

**Issue by BimalRajGyawali** [BimalRajGyawali/hacktoberfest-java#148]
It would be helpful if we can navigate to packages/folders by clicking a link on README.

**Comment by Varad0124** [comment]
Hey @BimalRajGyawali do you want all links to be shown in README from (https://github.com/BimalRajGyawali/hacktoberfest-java/tree/main/src/main/java/org)/example/ ?

**Comment by BimalRajGyawali** [comment]
Yes @Varad0124 . It should act like table of content or index.

**Comment by yashdkadam** [comment]
### **I would like to work on this task. Could you assign this issue to me?**

**Comment by BimalRajGyawali** [comment]
Done @yashdkadam
