### ISSUE TITLE
Adding codes for other keywords(this and final)

### ISSUE THREAD

**Issue by suryanshsoni120** [BimalRajGyawali/hacktoberfest-java#151]
@BimalRajGyawali In oops folder, there is a file for explaining static. Can I add files for final and this keywords?

**Comment by BimalRajGyawali** [comment]
Hi @suryanshsoni120, yes you can do that. 

Make sure to use proper naming conventions for packages(all lower cases), classes(CamelCase) and methods(camelCase).

**Comment by raikiran07** [comment]
I have sent a PR for the solution to this issue, including the solution of issue number #155, please review it and merge it if everything is fine.

**Comment by suryanshsoni120** [comment]
@BimalRajGyawali I have sent a PR for this keyword. Please go through it and merge it if there's no issue.
