### ISSUE TITLE
Reading from a file

### ISSUE THREAD

**Issue by BimalRajGyawali** [BimalRajGyawali/hacktoberfest-java#16]
Write a program in Java to read a text file line by line using java.io package

**Comment by Sscuber03** [comment]
Hello @BimalRajGyawali , I want to solve this issue, can this be assigned to me?

**Comment by BimalRajGyawali** [comment]
Done @Sscuber03

**Comment by Sscuber03** [comment]
Should i attach a text file also, or should i leave the path to text file as a placeholder, and write a comment about adding the path before running?

**Comment by Sscuber03** [comment]
Please check and accept, or please notify if anything wrong

**Comment by BimalRajGyawali** [comment]
@Sscuber03  Merged
