### ISSUE TITLE
Implement Jump Search program

### ISSUE THREAD

**Issue by Nikhil-2002** [BimalRajGyawali/hacktoberfest-java#161]
Please add label

**Comment by BimalRajGyawali** [comment]
Hi @Nikhil-2002, please add description for the issue.

**Comment by Nikhil-2002** [comment]
Implement jump search algorithm program using  java

**Comment by Nikhil-2002** [comment]
Please check @BimalRajGyawali and accept PR, Thanks

**Comment by BimalRajGyawali** [comment]
Hi @Nikhil-2002 , there is no any active PR.
