### ISSUE TITLE
Class and Objects

### ISSUE THREAD

**Issue by BimalRajGyawali** [BimalRajGyawali/hacktoberfest-java#19]
Write a program to create a sample class of your choice and create its objects.

**Comment by RockingRishav** [comment]
I want to work upon this issue,could you please assign me this issue?

**Comment by BimalRajGyawali** [comment]
Hi @RockingRishav , I have already assigned you to another issue as you requested. Once you complete that I will assign this to you too.

**Comment by aryan-upa** [comment]
Hey, Can you assign this to me? I'm a newbie in open-source...

**Comment by Vedant755** [comment]
Hey, can you assign it to me? I have a proper hold on the OOPS concept and would handle this issue perfectly!

**Comment by BimalRajGyawali** [comment]
Hi @aryan-upa  and @Vedant755 , thanks for showing interest.

You both can proceed with the issue. Each can separate two separate classes and their objects. Thanks.

**Comment by bhushan162** [comment]
can i work on this issue?

**Comment by BimalRajGyawali** [comment]
Hi @bhushan162 , yes you. Make a class you like and create its object. Thanks

**Comment by bhushan162** [comment]
done

**Comment by BimalRajGyawali** [comment]
Merged

**Comment by bhushan162** [comment]
can this is considered one of my pull request in Hacktoberfest?.

**Comment by Vedant755** [comment]
Hey, @BimalRajGyawali I am done with the pull request #25

**Comment by BimalRajGyawali** [comment]
Hi @Vedant755 , .DS_store files are included in the pull request which are not needed. Please delete them and push again.

**Comment by Vedant755** [comment]
#28

**Comment by BimalRajGyawali** [comment]
Merged

**Comment by Parvezi123** [comment]
Hi  @BimalRajGyawali , I have worked on the Inheritance Concept to create class and Objects
Will be Making a PullRequest, Please review it, and accept it if it look good. Thanks

**Comment by Parvezi123** [comment]
Hi @BimalRajGyawali ,
Can I create and Add Java - Spring-Based Projects? to get Counted for Hacktoberfest
Please let me know. Thanks

**Comment by nikitadudhbhate** [comment]
hey @BimalRajGyawali, can you assign it to me? I am a newbie in open source contribution and I have keen Knowledge of JAVA.

**Comment by BimalRajGyawali** [comment]
Hi @nikitadudhbhate, you can proceed with this issue.

**Comment by BimalRajGyawali** [comment]
> Hi @BimalRajGyawali ,
> Can I create and Add Java - Spring-Based Projects? to get Counted for Hacktoberfest
> Please let me know. Thanks

That would be a nice idea. You can create a new repo for that. This repo is only for Core Java targeted for the beginners.

**Comment by MaddyKilmurray** [comment]
Hi @BimalRajGyawali , I'd like to work on this, please. This will be my first opensource pull, hopefully!

**Comment by MaddyKilmurray** [comment]
Thanks @BimalRajGyawali! I have made a pull request, I wrote some generics examples

**Comment by BimalRajGyawali** [comment]
Hi @MaddyKilmurray, I have merged your PR. Thanks for contributing on Generics.
