### ISSUE TITLE
N-Ary tree Level Order Traversal

### ISSUE THREAD

**Issue by Yash-0813** [BimalRajGyawali/hacktoberfest-java#190]
@BimalRajGyawali Please assign me this issue .

**Comment by BimalRajGyawali** [comment]
Done @Yash-0813

**Comment by Nikhil-2002** [comment]
@BimalRajGyawali please assign me

**Comment by BimalRajGyawali** [comment]
Hi @Nikhil-2002, already assigned to @Yash-0813
