### ISSUE TITLE
Spirally traversing a matrix : Given an m x n matrix, return all elements of the matrix in spiral order.

### ISSUE THREAD

**Issue by panditsneha** [BimalRajGyawali/hacktoberfest-java#210]
@BimalRajGyawali Sir could you please assign me this issue and add a hacktoberfest label? I want to contribute.
![1](https://user-images.githubusercontent.com/82725681/195917002-076d42ff-2105-46f7-b7f1-e41da34e9f3f.png)
![2](https://user-images.githubusercontent.com/82725681/195917010-318635cb-b689-4c88-982d-037cecad6f13.png)

**Comment by BimalRajGyawali** [comment]
Done @panditsneha

**Comment by panditsneha** [comment]
Under which folder should I upload?

**Comment by BimalRajGyawali** [comment]
You can place it under algorithms folder/package.

**Comment by panditsneha** [comment]
Okay Thankyou

**Comment by panditsneha** [comment]
Initial commit #216. Kindly review.
