### ISSUE TITLE
Connect to MySQL database using java (JDBC)

### ISSUE THREAD

**Issue by Haaris-Sayyed** [BimalRajGyawali/hacktoberfest-java#220]
A program to demonstrate how to establish a connection with MySQL database using java.

**Comment by Haaris-Sayyed** [comment]
@BimalRajGyawali I would like to work on this issue, Could you please assign this to me?

**Comment by BimalRajGyawali** [comment]
Done @Haaris-Sayyed . Make a separate package named _jdbc_

**Comment by Pratikshaekbote** [comment]
I would like to work on this issue, Could you please assign this to me?

**Comment by BimalRajGyawali** [comment]
Hi @Pratikshaekbote , this is already implemented.
