### ISSUE TITLE
Famous leetcode solutions

### ISSUE THREAD

**Issue by arorasukhmani** [BimalRajGyawali/hacktoberfest-java#229]
Famous leetcode solutions like sodoku solver, n queens, etc.

**Comment by arorasukhmani** [comment]
Please assign me this issue and add hacktoberfest label to it

**Comment by 7smn2219** [comment]
I can do hard questions of leetcode such as
1 median of two sorted array
2 Trapping rain water
3 word ladder 
4 count smaller number after self 
5 poor pigs
etc.

**Comment by 7smn2219** [comment]
Please assign this to me and add hacktoberfest label to it

**Comment by BimalRajGyawali** [comment]
Done @7smn2219 .

Include one solution in one PR. Create a package _leetcode_ and place code there.

**Comment by anushagupta1312** [comment]
I want to add solutions to it. Can you assign it to me?

**Comment by BimalRajGyawali** [comment]
@anushagupta1312  done

**Comment by darkling10** [comment]
Hey there,I also want to add solutions to famous leetcode questions like
1.Longest Palindromic Subsequence
2.Trapping Rain water
3.Candy
etc

**Comment by Swayam101** [comment]
can you please assign this to me?

**Comment by BimalRajGyawali** [comment]
Done @Swayam101

**Comment by yashdkadam** [comment]
Could you please assign this to me? I am able to solve leetcode medium to hard level questions.

**Comment by Vaibhavraj-nath-chauhan** [comment]
Can you please assign this issue me

**Comment by BimalRajGyawali** [comment]
@yashdkadam @Vaibhavraj-nath-chauhan  you can proceed with this issue. Make sure not to implement already implemented problems.
