### ISSUE TITLE
Missing Data in Readme.md for Collections

### ISSUE THREAD

**Issue by darkling10** [BimalRajGyawali/hacktoberfest-java#329]
The Readme.md file has an empty Readme. Can I write the Readme for that?

**Comment by darkling10** [comment]
Please assign me this issue and add hacktoberfest label to it

**Comment by BimalRajGyawali** [comment]
Hi @darkling10, can you explain what you mean by _empty Readme_ ? What data you want to add?

**Comment by BimalRajGyawali** [comment]
There is also another issue regarding the enhancement of Readme https://github.com/BimalRajGyawali/hacktoberfest-java/issues/148. You can contribute to it as well.

**Comment by darkling10** [comment]
@BimalRajGyawali we can add notes for Collection Frameworks

**Comment by BimalRajGyawali** [comment]
Ok @darkling10 . I have assigned this to you.
