### ISSUE TITLE
Some of the sorting methods are missing

### ISSUE THREAD

**Issue by yashdkadam** [BimalRajGyawali/hacktoberfest-java#344]
Some of the sorting technique implementations in java are not present in the repository.
We can include:

- Iterative Merge Sort
- Iterative Quick Sort
- TimSort
- Comb Sort
- Pigeonhole Sort
- Cycle Sort
- Cocktail Sort
- Strand Sort

**Comment by yashdkadam** [comment]
I am interested on work on this task. Could you assign the issue to me?

**Comment by BimalRajGyawali** [comment]
Done @yashdkadam

**Comment by BimalRajGyawali** [comment]
@yashdkadam  please go through the whole repo once. Attempt only those not present already. Stack, queues, prime and string algorithms are already present.
