### ISSUE TITLE
Some of the searching techniques in java are missing

### ISSUE THREAD

**Issue by yashdkadam** [BimalRajGyawali/hacktoberfest-java#345]
The following java methods of searching are not present in the repository:

- Interpolation Search
- Exponential Search
- Sublist Search 
- Fibonacci Search
- The Ubiquitous Binary Search

**Comment by yashdkadam** [comment]
### **I am interested to work on this task. Could you please assign this issue to me?**

**Comment by BimalRajGyawali** [comment]
lease go through the whole repo once. Attempt only those not present already. Stack, queues, prime and string algorithms are already present. 

Also, include only one file in one PR. Follow naming conventions.

**Comment by BimalRajGyawali** [comment]
Done @vishnoitanuj

**Comment by vishnoitanuj** [comment]
Thanks, added [PR](https://github.com/BimalRajGyawali/hacktoberfest-java/pull/391)
