### ISSUE TITLE
Interface Implementation 

### ISSUE THREAD

**Issue by BimalRajGyawali** [BimalRajGyawali/hacktoberfest-java#40]
Create an interface and its implementation class.

**Comment by nikitadudhbhate** [comment]
hi, @BimalRajGyawali Can u assign this to me? I want to contribute.

**Comment by BimalRajGyawali** [comment]
Done @nikitadudhbhate

**Comment by panditsneha** [comment]
Sir could you please assign this issue to me?

**Comment by shivzz-creator** [comment]
sir can you please me this ?

**Comment by shivzz-creator** [comment]
sir can you please add me as contributor as i want to add my implementation ?

**Comment by BimalRajGyawali** [comment]
@panditsneha @shivzz-creator  I have this assigned this issue to you. You can work on this.

**Comment by shivzz-creator** [comment]
https://github.com/BimalRajGyawali/hacktoberfest-java/pull/57 
It is done sir !!

**Comment by panditsneha** [comment]
Issue #59 Done.

**Comment by panditsneha** [comment]
Changes done #66 (Deleted .class file)
