### ISSUE TITLE
Add basic java codes

### ISSUE THREAD

**Issue by Haaris-Sayyed** [BimalRajGyawali/hacktoberfest-java#55]
Add some beginner friendly basic java codes

**Comment by Haaris-Sayyed** [comment]
@BimalRajGyawali I would like to work on this issue, could you please assign this to me?

**Comment by arorasukhmani** [comment]
I would like to work on this issue

**Comment by gandhi25samar** [comment]
I would like to work on this issue

**Comment by BimalRajGyawali** [comment]
Hi @gandhi25samar  @arorasukhmani , you can proceed with this issue

**Comment by AditiBendre** [comment]
can i contribute to this issue?

**Comment by gandhi25samar** [comment]
Hey @BimalRajGyawali I have sent a PR. Please merge it and let me know

**Comment by ArcheR1901** [comment]
hello @BimalRajGyawali can i work on this issue, can you assign this to me?

**Comment by Nikhil-2002** [comment]
hey @BimalRajGyawali sir I would like to work on this issue, can you assign this to me?

**Comment by BimalRajGyawali** [comment]
Hi @ArcheR1901 @Nikhil-2002, you can proceed with this issue. Thanks

**Comment by Nikhil-2002** [comment]
Hey, @BimalRajGyawali I have sent a PR. Please merge it and let me know

**Comment by BimalRajGyawali** [comment]
I am closing this issue as repo has been crowded with basic codes. Thanks for the contribution.
