### ISSUE TITLE
Adding Implementation of Sorting Algorithms in Java

### ISSUE THREAD

**Issue by yazh1202** [BimalRajGyawali/hacktoberfest-java#56]
I would like to add implementations of popular sorting algorithms such as Merge Sort,Quick Sort, Bubble Sort etc.

**Comment by yazh1202** [comment]
Could you please assign this to me @BimalRajGyawali ?

**Comment by BimalRajGyawali** [comment]
Hi @yazh1202, you can proceed with this issue

**Comment by gandhi25samar** [comment]
Hi @yazh1202 please assign me this issue

**Comment by BimalRajGyawali** [comment]
Hi @gandhi25samar, you can proceed with this issue

**Comment by gandhi25samar** [comment]
Hey @BimalRajGyawali I have sent a PR. Please merge it and let me know.

**Comment by Nikhil-2002** [comment]
Hi @BimalRajGyawali please assign me this issue

**Comment by BimalRajGyawali** [comment]
Hi @Nikhil-2002, you can work on this.

**Comment by Yadnyesh-Dashpute** [comment]
Hi @BimalRajGyawali I Would Like to Add popular sorting Alogorithms like Bubble Sort, Merge Sort, Quick Sort etc.

**Comment by BimalRajGyawali** [comment]
I am closing this issue as changes have been already merged. Thanks for the contribution.
