### ISSUE TITLE
Adding algorithms Folder

### ISSUE THREAD

**Issue by bagariaraj23** [BimalRajGyawali/hacktoberfest-java#65]
Hey, i want to add an algorithms folder in which we can contribute with the source codes of some famous algorithms like Dijkstra's algorithm, FLoyd-Warshall's algorithm, Hamiltonian cycles, Prims and kruskal's algorithm, etc.
This way we can create a separate collection of all the algorithms.

**Comment by bagariaraj23** [comment]
Also i would love to contribute with the source code of a few algorithms. Assign the task and provide some labels if it suits you.

**Comment by BimalRajGyawali** [comment]
Thanks @bagariaraj23 for the initiation. I have assigned this issue to you.

**Comment by Nikhil-2002** [comment]
hello @BimalRajGyawali Please Assign me this issue

**Comment by bagariaraj23** [comment]
hey @Nikhil-2002 i've already been working on this issue and have already raised a PR, waiting for @BimalRajGyawali for the further confirmation.

**Comment by BimalRajGyawali** [comment]
Hi @Nikhil-2002, @bagariaraj23 is already working on this.

**Comment by BimalRajGyawali** [comment]
Hi @bagariaraj23, there is no open PR. Can you check once?

**Comment by bagariaraj23** [comment]
yeah, i checked it, it has already been merged. Thank you! I'll be contributing with more Algorithms soon.
