### ISSUE TITLE
Add LinkedList implementation Folder

### ISSUE THREAD

**Issue by gandhi25samar** [BimalRajGyawali/hacktoberfest-java#67]
Hey @BimalRajGyawali I would like to add linkedList implementation with some of the basic operations and some advanced like detecting a cycle in linked list, palindrome, remove nth node from end. So please assign me this issue and add the hacktoberfest label.

**Comment by BimalRajGyawali** [comment]
Hi @gandhi25samar. Thanks for the initiation

**Comment by gandhi25samar** [comment]
Hey @BimalRajGyawali I have sent a PR. Please merge it and let me know

**Comment by BimalRajGyawali** [comment]
The changes have been merged. I am closing this issue. Thanks for the contribution @gandhi25samar .
