### ISSUE TITLE
Implement OOPS concept in Java

### ISSUE THREAD

**Issue by vallabhiaf** [BimalRajGyawali/hacktoberfest-java#77]
This issue will contribute to the basic Oops code which people can refer to keep as an oops refresher!
Looking forward for you to assign this me

**Comment by BimalRajGyawali** [comment]
@vallabhiaf Done

**Comment by Nikhil-2002** [comment]
Hi @BimalRajGyawali please assign me this issue

**Comment by panditsneha** [comment]
Sir could you please assign this issue to me?

**Comment by BimalRajGyawali** [comment]
Hi @Nikhil-2002, @panditsneha you can work on this

**Comment by panditsneha** [comment]
Implemented OOPS in java #95 . Kindly review my code.

**Comment by vallabhiaf** [comment]
> @vallabhiaf Done

Please lookout for my PR and share feedback:)

**Comment by BimalRajGyawali** [comment]
I am closing this issue as it is completed. Thanks for the contribution.
