### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by BimalRajGyawali** [BimalRajGyawali/hacktoberfest-java#8]
Add a contributing.md file stating steps of contribution

**Comment by GulamMd** [comment]
Interested thanks in advance

**Comment by GulamMd** [comment]
Hi i have raised a PR please review once...Thanks

**Comment by BimalRajGyawali** [comment]
Hi @GulamMd, I have created a CONTRIBUTING.md file with steps. Can you add the content there instead of a new file?
