### ISSUE TITLE
Implementation of functions in Java

### ISSUE THREAD

**Issue by gandhi25samar** [BimalRajGyawali/hacktoberfest-java#86]
Hey @BimalRajGyawali I would like to add the basic and some advance codes about how functions are implemented in Java. Please assign me this issue and add the Hacktoberfest label.

**Comment by BimalRajGyawali** [comment]
Sure, proceed with this issue.

Make sure to **include only smaller number of changes** with appropriate files, class and method names.

Place the code in appropriate package.

Thanks.

**Comment by gandhi25samar** [comment]
Hey @BimalRajGyawali I have sent a PR. Please merge it and let me know.

**Comment by BimalRajGyawali** [comment]
Hi @gandhi25samar, I have requested some changes. Please look at it. Thanks

**Comment by gandhi25samar** [comment]
I have made the changes and sent a new PR. Please merge it and let me know.

**Comment by BimalRajGyawali** [comment]
@gandhi25samar Merged! Thanks for contribution.
